version: '3' # Версия Docker Compose
services:
  redis:
    image: redis:alpine  # Используемое изображение Redis на базе Alpine Linux
    ports:
      - "6379:6379" # Пробрасывание порта 6379 на хост-машину
  postgres:
    image: postgres:16 # Используемое изображение PostgreSQL версии 16
    environment:
      POSTGRES_DB: ${PG_DB} # Имя базы данных
      POSTGRES_USER: ${PG_USER} # Имя пользователя базы данных
      POSTGRES_PASSWORD: ${567234} # Пароль пользователя базы данных

    ports:
      - "5432:5432" # Пробрасывание порта 5432 на хост-машину
    volumes:
      - ./postgres-data:/var/lib/postgresql/data # Монтирование локальной директории для хранения данных PostgreSQL

# docker run --name db-postgres -p 5432:5432 -e POSTGRES_PASSWORD=567234 -d postgres